export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const GET_USER_WITH_FETCH = 'GET_USER_WITH_FETCH';
export const GET_USER_WITH_AXIOS = 'GET_USER_WITH_AXIOS';
export const REMOVE_USER = 'REMOVE_USER';
